# ====================basis.connection====================
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/imm_kk?useUnicode=true&characterEncoding=utf8&serverTimezone=Hongkong&autoReconnect=true&failOverReadOnly=false
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080

#mybatis config
mybatis-plus:
#  config-location: classpath:mybatis/mybatis-config.xml
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.imm.kk.entity
  mybatis-plus.config-location: classpath:mybatis/mybatis-config.xml
  mybatis-plus.mapper-locations: classpath:mapper/*.xml
  mybatis-plus.type-aliases-package: com.imm.kk.entity
