# ====================basis.connection====================
spring:
  datasource:
    url: jdbc:mysql://192.168.8.163:3306/imm_kk?useUnicode=true&characterEncoding=utf8&serverTimezone=Hongkong&autoReconnect=true&failOverReadOnly=false
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080

#mybatis config
mybatis-plus:
#  config-location: classpath:mybatis/mybatis-config.xml
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.imm.kk.entity
#  mybatis-plus.config-location: classpath:mybatis/mybatis-config.xml
  mybatis-plus.mapper-locations: classpath:mapper/*.xml
  mybatis-plus.type-aliases-package: com.imm.kk.entity
  mybatis-plus.configuration.map-underscore-to-camel-case: true

  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
    refresh: false
    configuration:
      map-underscore-to-camel-case: true
      cache-enabled: false
